### ISSUE TITLE
news items

### ISSUE THREAD

**Issue by sckott** [ropensci/helminthR#21]
nice work on the new release  👌 

was preparing ropensci news, and trying to quickly capture what I should highlight in your latest release  

The stuff in https://github.com/ropensci/helminthR/blob/master/NEWS.md#helminthr-107 doesn't seem to match what's in https://github.com/ropensci/helminthR/releases/tag/v.1.0.7 - Ideally you can just copy/paste from NEWS.md into your release notes and not re-write it. 

This section in our guide https://ropensci.github.io/dev_guide/releasing.html#news has notes on how to do news/release notes. Thanks!

**Comment by taddallas** [comment]
Nice. Thanks for passing that along. I can update the news.md file to match the release notes. Good idea?

It contains the same info, just in different words though. It's a tiny update to remove the `ggmap` dependency (revdep conflict lead me to strip away now broken functionality) and fix a small issue in the `cleanData` function to better clean away species identified to "spp." instead of just "sp.". That extra "p" is **important**.

**Comment by sckott** [comment]
news and release notes don't have to match exactly. but it's just a suggestion for making things easier for yourself. On top of copying over news items to release, some embellish with other things, e.g., see https://github.com/ropensci/RNeXML/releases/tag/v2.3.0 , or you can put a link in to compare to previous release https://github.com/ropensci/taxize/releases/tag/v0.9.5 etc. but extra stuff is very optional and depends on your use case. 

ah yes, spp vs sp

**Comment by taddallas** [comment]
Makes sense. I'll incorporate it into future releases and news updates. Closing the issue, but with some best practices learned. :smile:
